# -*- coding: utf-8 -*-

quotes =  [
    "The ink of a scholar is worth a thousand times more than the blood of a martyr -- Lupe Fiasco",
    "Everyday women and men become legends -- Common",
    "No matter how hard it gets, stick your chest out, keep your head up and handle it -- Tupac",
    "Reach for the stars so if you fall you land on the clouds -- Kanye West",
    "Keep integrity at every cost -- Nas",
    "I took my bruises, took my lumps, fell down and got right back up -- Eminem",
    "Everybody dies but not everybody lives -- Drake",
    "Bow in the presence of greatness -- Kanye West",
    "Everything is everything. What is meant to be, will be -- Lauryn Hill",
    "Nevermind what the haters say, ignore em til they fade away -- T.I.",
    "Life without knowledge is death in disguise -- Talib Kweli",
    "Never become so involved with something that it blinds you. Never forget where you from; someone will remind you. -- DMX",
    "Life is a wheel of fortune and it’s my turn to spin it. -- Tupac",
    "Life is too short to live the same day twice. So each new day make sure you live your life. -- Machine Gun Kelly",
    "Life without dreaming is a life without meaning. -- Wale",
    "If you admire someone, you should go ahead and tell them. People never get the flowers while they can still smell them -- Kanye West",
    "Love yourself and your expression, you can’t go wrong. --KRS One",
    "Me and my people break bread, sit and smoke. The conversation rich, but that depend on what you consider broke -- Talib Kweli",
    "Everyday is a new opportunity to reach that goal. -- Rick Ross",
    "Be more concerned with your character than your reputation. Because your character is what you really are. While your reputation is what others merely think you are. -- Jay Z",
    "Some seek fame cause they need validation, Some say hating is confused admiration. -- Nas",
    "They say a midget standing on a giant’s shoulders can see much further than the giant. So I got the whole rap world on my shoulders, they trying to see further than I am -- Jay Z",
    "Even though you’re fed up, you got to keep ya head up. -- Tupac",
    "They’re gonna try to tell you no, shatter all your dreams. But you gotta get up and go and think of better things. -- Mac Miller",
    "Never apologize for what you feel. It’s like apologizing for being real. -- Lil Wayne",
    "How many people you bless, is how you measure success -- Rick Ross"
    ]
